### ISSUE TITLE
issue package 5.4.16 and 5.4.45

### ISSUE THREAD

**Issue by tanguybernard** [geerlingguy/ansible-role-phpmyadmin#10]
Hello,
Firstly, thank you @geerlingguy :)

I'm trying to build a lamp. Everything fine until I add "geerlingguy.phpmyadmin"
Vagrant OS : **geerlingguy/centos7**

playbook.yml

```
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - { role: geerlingguy.mysql, become: yes}
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.git
    - geerlingguy.composer
    - geerlingguy.phpmyadmin
```

my php_packages:

```
  - php
  - php-cli
  - php-common
  - php-devel
  - php-gd
  - php-mbstring
  - php-pdo
  - php-pecl-apcu
  - php-xml
  - php-bcmath
  - php-mysql
```
1. sudo ansible-galaxy install -r requirements.yml --force
2. vagrant up

step 2 at the end:

`TASK [geerlingguy.phpmyadmin : Ensure PHPMyAdmin is installed.] ****************
fatal: [lamp]: FAILED! => {"changed": true, "failed": true, "msg": "Error: Package: php-process-5.4.16-36.1.el7_2.1.x86_64 (updates)\n           Requires: php-common(x86-64) = 5.4.16-36.1.el7_2.1\n           Installed: php-common-5.4.45-11.el7.remi.x86_64 (@remi)\n               php-common(x86-64) = 5.4.45-11.el7.remi\n           Available: php-common-5.4.16-36.el7_1.x86_64 (base)\n               php-common(x86-64) = 5.4.16-36.el7_1\n           Available: php-common-5.4.16-36.1.el7_2.1.x86_64 (updates)\n               php-common(x86-64) = 5.4.16-36.1.el7_2.1\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: centos.quelquesmots.fr\n * epel: mirror.ibcp.fr\n * extras: centos.quelquesmots.fr\n * remi-safe: remi.mirror.ate.info\n * updates: centos.quelquesmots.fr\nResolving Dependencies\n--> Running transaction check\n---> Package phpMyAdmin.noarch 0:4.4.15.7-1.el7 will be installed\n--> Processing Dependency: php-tcpdf-dejavu-sans-fonts for package: phpMyAdmin-4.4.15.7-1.el7.noarch\n .....`

Can you help me please ?

Tanguy

**Comment by geerlingguy** [comment]
It looks like you're using Remi's repository for a later version of PHP (e.g. 5.4), but this role currently only works with `epel` (see https://github.com/geerlingguy/ansible-role-phpmyadmin/blob/master/tasks/setup-RedHat.yml#L3).

Would you like to be able to set the repo used for the installation? In that case, you could set something like `phpmyadmin_repo: remi` and it should install correctly.

**Comment by geerlingguy** [comment]
Please see https://github.com/geerlingguy/ansible-role-phpmyadmin/commit/23e16aa78eec9a80cc6e67719dfb5294ac5b35fe - and see the test included in the tests directory for an example of using it with PHP 7.
