### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by igormukhingmailcom** [geerlingguy/ansible-role-phpmyadmin#2]
First of all want to say thank you, @geerlingguy, for good roles.

But there is one moment.
Lets imagine that I select not your role to install apache (let say mine).
And if I want to install your phpmyadmin role - I need fork phpmyadmin role, remove unwanted dependencies and even publish it at galaxy.ansible.com to use it in requirements.txt, because otherwise apache role will run twice - one mine and one your from dependencies.

How you think, maybe will be better to delete dependencies from meta and just write about that in README? Or maybe you can advice something?

This question also about many other your roles that have dependencies.
Thak you for answer.

**Comment by geerlingguy** [comment]
For this role it's a little tricky, since I rely on the Apache role's `restart apache` handler... we'd have to rearchitect things a little to make it independent (and to work with both Nginx and Apache, and/or FPM).

**Comment by Sispheor** [comment]
Yes, also this role force an install of Mysql. 
If I want to only use this role to install PMA I can't.

**Comment by geerlingguy** [comment]
We could also do this like how I do it in the PHP role, where there's a `restart webserver` handler in the php role, and a variable that defaults to `php_webserver: apache` or something like that.

**Comment by lucap73** [comment]
Hi Jeff,
I like all your Ansible role compliments!

I have a little request for the role "geerlingguy.phpmyadmin", I don't want to install mysql-server,
I would like to remove dependencies role "geerlingguy.mysql".

I modifided manually the file meta/mail.yml, but when I update your role with ansible-galaxy, it's override the file.

Can you help me please?
