### ISSUE TITLE
Suggestion: domain-based vhost

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-phpmyadmin#4]
A small but useful addition to this really helpful role would be to add a simple vhost to configure an actual domain path to it in stead of or in addition to the fixed /phpmyadmin path.

It would be more logical to visit it at http://phpmyadmin.local or another configurable (by variable) path.

**Comment by fubarhouse** [comment]
So this one has since been closed using drupal-vm's config, so I'll close it. Feel free to re-open it.

**Comment by fama** [comment]
I had the same problem.  If you are running an app such as drupal or magento which does rewrites, you need to run the phpmyadmin as a subdomain.
